ip: 192.168.1.3
asset: AB1VLaser

tags:
  CHECK_TAG: 'Verify_Barcode'
  CODE_TAG: 'Laser_QR_Code_Text'
  GOOD_TAG: 'Barcode_OK'
  BAD_TAG: 'Barcode_Not_OK'
  LASER_JOB: 'Part_Detected_To_Run'

# map the value of LASER_JOB tag to database part numbers
part_mapping:
  '50-8670': '50-8670'
  '50-5401': '50-5401'
  '50-0450': '50-0450'
  '50-0447': '50-0447'
  '50-5404': '50-5404'
  '50-0519': '50-0519'
  '50-3214': '50-3214'
  '50-5214': '50-5214'
